name: orchestrate-approval-workflow
run-name: ${{ github.actor }} is deploying using GitHub Actions
on: workflow_dispatch
jobs:
    
  deploy-to-devtest:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy'
      
  deploy-Prod-workflow-passing-data:
    needs: deploy-to-devtest
    uses: ./.github/workflows/deploy.yml
    #uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      environment: Production
      project_id: sab-dev-cicd-7522
